---
title: "PS5_Draft_2"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())

library(foreign)
library(ggplot2)
library(lpdensity)
library(rddensity)
library(rdrobust)
library(rdlocrand)
library(TeachingDemos)
library(formattable)
library(jtools)
library(broom)
library(ggpubr)
library(dplyr)
library(tidyverse)
library(skimr)
library(caret)
library(car)
```
```{r echo=TRUE}
df <- read.csv("Cambridge_education.csv")
```
```{r pressure, echo=TRUE}
head(df)

# factorize all the categorical variable
df$male <- as.factor(df$male)
df$bpl_north_america <- as.factor(df$bpl_north_america)
df$english <- as.factor(df$english)
df$loc_campus1 <- as.factor(df$loc_campus1)
df$loc_campus2 <- as.factor(df$loc_campus2)
df$loc_campus3 <- as.factor(df$loc_campus3)

summary(df$left_school)

# calculate how many student were put on probation
df %>% filter(T == 0) %>% count() #37211

# calculate how many student were put on porbation and left school
df %>% filter(T == 0) %>% 
  filter(left_school == 1) %>% count() #1386

# Data pre-processing

# get summary statistics for dataset
summary(df) %>% formattable()

# generate a new column named probation as a factor version of the variable T
df <- df %>% mutate(probation = if_else(T == 0, "yes", "no")) 
df$probation <- as.factor(df$probation)
# generate a new column that separates the students into two groups based on their high school grade percentage
df <- df %>%
  mutate(hsgrade_50_sep = ifelse(hsgrade_pct < 50, "lower", "upper"))

# factorize probation status variable
df$probation <- as.factor(df$probation)

# remove all rows with NA
df_cleaned <- na.omit(df)

```
```{r include=FALSE}
# calcualte the count of the students who is on probation and left school based on gender and high school grade
df %>% 
  filter(T == 0) %>%
  filter(left_school == 1) %>%
  group_by(male, hsgrade_50_sep) %>%
  count()

# calcualte the count of the students who is on probation and left school based on native language and birth place
df %>%
  filter(T == 0) %>%
  filter(left_school == 1) %>%
  group_by(english, bpl_north_america) %>%
  count()

# calcualte the count of the students who is on probation and left school based on campus 
df %>%
  filter(T == 0) %>%
  filter(left_school == 1) %>%
  group_by(loc_campus1, loc_campus2, loc_campus3) %>%
  count()

```
```{r include=FALSE}
attach(df_cleaned)
# graph 1 the compliance status of students towards probation
ggplot(data=df, aes(x = df$X, fill = probation))+
  geom_histogram(breaks=seq(-2.8, 0, by = 0.1), col="black", alpha = 1)+
  geom_histogram(breaks=seq(0, 1.6, by = 0.1), col="white", alpha = 1)+
  labs(y = "Number of Observation",
       x = "Previous year GPA minus probation cutoff",
       color = "Probation") + geom_vline(xintercept=0, color="black")+
  theme_bw() +
  ggtitle("Graph 1: Compliance status of Students towards probation") 


# Graph 2: Number of students' GPAs separated by probation status
ggplot(data = df_cleaned, aes(x = X, fill = probation)) +
  geom_histogram(binwidth = 0.08, position = "dodge") +
  ggtitle("Graph 2: Number of students' GPAs separated by probation status") + 
  labs(y = "Number of Observations",
       x = "Previous year GPA minus probation cutoff",
       color = "Probation")

# Graph 3: Number of students GPAs after probation separated by probation status
ggplot(data = df_cleaned, aes(x = nextGPA, fill = probation)) + 
  geom_histogram(binwidth = 0.08, position = "dodge") + 
  ggtitle("Graph 2: Number of students GPAs after probation separated by probation status")+ 
  labs(y = "Number of Observations",
       x = "Next year GPA minus probation cutoff",
       color = "Probation")

# Graph 4: Changes in GPA for all students
rdplot(df$nextGPA, df$X, 
       x.label = "Previous year GPA minus probation cutoff", 
       y.label = "Next year GPA minus probation cutoff", 
       title="Graph 3: Changes in GPA for all students")

```
```{r}
# Linear regression model

# In order to get the correct result, after running this model, remember to clear variables before running next
# Split the data into training and test set for df_cleaned
## 75% of the sample size
smp_size_cleaned <- floor(0.75 * nrow(df_cleaned))

## set the seed to make your partition reproducible
set.seed(123)
train_ind_cleaned <- sample(seq_len(nrow(df_cleaned)), size = smp_size_cleaned)

train_cleaned <- df_cleaned[train_ind_cleaned, ]
test_cleaned <- df_cleaned[-train_ind_cleaned, ]

model_lm <- lm(nextGPA ~ probation + hsgrade_pct + totcredits_year1 + age_at_entry + male + english + loc_campus1 + loc_campus2, data = train_cleaned)
# Summarize the model
summary(model_lm)

# Make predictions
predictions <- model_lm %>% predict(test_cleaned)
predictions
# Model performance
# (a) Prediction error, RMSE
RMSE(predictions, test_cleaned$nextGPA)
# (b) R-square
R2(predictions, test_cleaned$nextGPA)
# looking for plot analysis
plot(model_lm)

```
```{r}
rm(list=ls())
df <- read.csv("Cambridge_education.csv")
df_cleaned <- na.omit(df)
# Another linear regression model
# filter the dataset to get more zoomed range of the observation around the probation cutoff
df_Xclosely <- filter(df_cleaned, X > -0.25 & X < 0.25)

## 75% of the sample size
smp_size <- floor(0.75 * nrow(df_Xclosely))

## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(df_Xclosely)), size = smp_size)

train <- df_Xclosely[train_ind, ]
test <- df_Xclosely[-train_ind, ]

# build the model using observations around the cut off
model_closely <- lm(nextGPA ~ probation + hsgrade_pct + totcredits_year1 + age_at_entry + male + english + loc_campus1 + loc_campus2, data = train)
summary(model_closely)

# Make predictions
predictions <- model_closely %>% predict(test)
predictions
# Model performance
# (a) Prediction error, RMSE
RMSE(predictions, test$nextGPA)
# (b) R-square
R2(predictions, test$nextGPA)
# looking for plot analysis
plot(model_closely)
```

